application: engineapp
version: 1
runtime: python27
api_version: 1
threadsafe: True

handlers:

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /css
  static_dir: inc/css

- url: /js
  static_dir: inc/js

- url: /images
  static_dir: inc/images

- url: /fonts
  static_dir: inc/fonts

- url: .*
  script: main.app

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: django
  version: "latest"

